# Generated by Django 3.2.8 on 2021-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman'), (3, 'Supplement')]),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
