# Generated by Django 3.2.8 on 2021-11-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211107_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('S', 'Supplement')], max_length=1),
        ),
    ]
